"""Minimal i18n: user-facing strings with language fallback."""

from __future__ import annotations

from telegram import Update

_FALLBACK = "en"

_STRINGS: dict[str, dict[str, str]] = {
    "welcome": {
        "en": (
            "Hi! Send me an image generated by Google Gemini and I'll remove "
            "the watermark for you.\n\n"
            "You can send photos (compressed) or files (full resolution). "
            "Multiple images at once are supported too."
        ),
        "pl": (
            "Hej! Wyślij mi obraz wygenerowany przez Google Gemini, "
            "a usunę z niego znak wodny.\n\n"
            "Możesz wysyłać zdjęcia (skompresowane) lub pliki (pełna rozdzielczość). "
            "Obsługiwane jest też wiele obrazów naraz."
        ),
    },
    "processing": {
        "en": "Processing…",
        "pl": "Przetwarzanie…",
    },
    "not_an_image": {
        "en": "That doesn't look like an image. Please send a photo or image file.",
        "pl": "To nie wygląda na obraz. Wyślij zdjęcie lub plik graficzny.",
    },
    "error": {
        "en": "Something went wrong while processing the image.",
        "pl": "Coś poszło nie tak podczas przetwarzania obrazu.",
    },
    "processing_batch": {
        "en": "Processing {count} images…",
        "pl": "Przetwarzanie {count} obrazów…",
    },
    "done_batch": {
        "en": "Done — processed {success}/{total} images.",
        "pl": "Gotowe — przetworzono {success}/{total} obrazów.",
    },
    "help": {
        "en": (
            "*How to use this bot:*\n\n"
            "1\\. Send me a photo or image file generated by Google Gemini\n"
            "2\\. I'll remove the watermark and send back a preview \\+ full\\-res file\n"
            "3\\. Send multiple images at once — I'll process them as a batch\n"
            "4\\. Send a \\.zip archive of images — I'll return a cleaned \\.zip\n\n"
            "*Commands:*\n"
            "/start \\- Welcome message\n"
            "/help \\- This help message\n"
            "/history \\- Your recently processed images\n\n"
            "*Inline mode:* Type @gemini\\_watermark\\_best\\_bot in any chat "
            "to share your recently processed images\\.\n\n"
            "Daily limit: {limit} images per day\\."
        ),
        "pl": (
            "*Jak używać tego bota:*\n\n"
            "1\\. Wyślij mi zdjęcie lub plik graficzny wygenerowany przez Google Gemini\n"
            "2\\. Usunę znak wodny i wyślę podgląd \\+ plik w pełnej rozdzielczości\n"
            "3\\. Wyślij wiele obrazów naraz — przetworzę je w partii\n"
            "4\\. Wyślij archiwum \\.zip z obrazami — zwrócę oczyszczone \\.zip\n\n"
            "*Komendy:*\n"
            "/start \\- Wiadomość powitalna\n"
            "/help \\- Ta wiadomość pomocy\n"
            "/history \\- Ostatnio przetworzone obrazy\n\n"
            "*Tryb inline:* Wpisz @gemini\\_watermark\\_best\\_bot w dowolnym czacie, "
            "aby udostępnić ostatnio przetworzone obrazy\\.\n\n"
            "Limit dzienny: {limit} obrazów dziennie\\."
        ),
    },
    "rate_limit_reached": {
        "en": "You've reached your daily limit of {limit} images. Try again tomorrow!",
        "pl": "Osiągnąłeś dzienny limit {limit} obrazów. Spróbuj ponownie jutro!",
    },
    "processing_zip": {
        "en": "Processing ZIP archive ({count} images)…",
        "pl": "Przetwarzanie archiwum ZIP ({count} obrazów)…",
    },
    "progress": {
        "en": "Processing {current}/{total}…",
        "pl": "Przetwarzanie {current}/{total}…",
    },
    "zip_done": {
        "en": "Done — processed {success}/{total} images from the archive.",
        "pl": "Gotowe — przetworzono {success}/{total} obrazów z archiwum.",
    },
    "zip_no_images": {
        "en": "No images found in the ZIP archive.",
        "pl": "Nie znaleziono obrazów w archiwum ZIP.",
    },
    "not_a_zip": {
        "en": "That doesn't look like a valid ZIP archive.",
        "pl": "To nie wygląda na prawidłowe archiwum ZIP.",
    },
    "history_empty": {
        "en": "No processed images in your history yet. Send me an image to get started!",
        "pl": "Brak przetworzonych obrazów w historii. Wyślij mi obraz, aby zacząć!",
    },
    "history_title": {
        "en": "Your recent images ({count}):",
        "pl": "Twoje ostatnie obrazy ({count}):",
    },
    "inline_open_bot": {
        "en": "Open bot to process images",
        "pl": "Otwórz bota, aby przetworzyć obrazy",
    },
}


def lang(update: Update) -> str | None:
    """Extract the user's language code from a Telegram update."""
    user = update.effective_user
    return user.language_code if user else None


def t(key: str, language: str | None = None, /, **kwargs: object) -> str:
    """Look up a translated string, falling back to English."""
    strings = _STRINGS[key]

    if language and language in strings:
        template = strings[language]
    elif language and language.split("-")[0] in strings:
        template = strings[language.split("-")[0]]
    else:
        template = strings[_FALLBACK]

    return template.format(**kwargs) if kwargs else template
