"""Minimal i18n: user-facing strings with language fallback."""

from __future__ import annotations

from telegram import Update

_FALLBACK = "en"

_STRINGS: dict[str, dict[str, str]] = {
    "welcome": {
        "en": (
            "Hi! Send me an image generated by Google Gemini and I'll remove "
            "the watermark for you.\n\n"
            "You can send photos (compressed) or files (full resolution). "
            "Multiple images at once are supported too."
        ),
        "pl": (
            "Hej! Wyślij mi obraz wygenerowany przez Google Gemini, "
            "a usunę z niego znak wodny.\n\n"
            "Możesz wysyłać zdjęcia (skompresowane) lub pliki (pełna rozdzielczość). "
            "Obsługiwane jest też wiele obrazów naraz."
        ),
    },
    "processing": {
        "en": "Processing…",
        "pl": "Przetwarzanie…",
    },
    "not_an_image": {
        "en": "That doesn't look like an image. Please send a photo or image file.",
        "pl": "To nie wygląda na obraz. Wyślij zdjęcie lub plik graficzny.",
    },
    "error": {
        "en": "Something went wrong while processing the image.",
        "pl": "Coś poszło nie tak podczas przetwarzania obrazu.",
    },
    "processing_batch": {
        "en": "Processing {count} images…",
        "pl": "Przetwarzanie {count} obrazów…",
    },
    "done_batch": {
        "en": "Done — processed {success}/{total} images.",
        "pl": "Gotowe — przetworzono {success}/{total} obrazów.",
    },
}


def lang(update: Update) -> str | None:
    """Extract the user's language code from a Telegram update."""
    user = update.effective_user
    return user.language_code if user else None


def t(key: str, language: str | None = None, /, **kwargs: object) -> str:
    """Look up a translated string, falling back to English."""
    strings = _STRINGS[key]

    if language and language in strings:
        template = strings[language]
    elif language and language.split("-")[0] in strings:
        template = strings[language.split("-")[0]]
    else:
        template = strings[_FALLBACK]

    return template.format(**kwargs) if kwargs else template
